baseurl = "https://codylewis.net"
languageCode = "en-us"
title = "Cody Lewis"
copyright = "Copyright &copy; {year} - Cody Lewis"
canonifyurls = true
theme = "kiera"

preserveTaxonomyNames= true
disqusShortname = "codylewis-net"
googleAnalytics = "UA-135439252-1"

paginate = 10

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30

[author]
    name = "Cody Lewis"
    github = "codylewis"
    gitlab = ""
    linkedin = "codyslewis"
    facebook = ""
    twitter = "codylewis87"
    instagram = ""

[params]
    description = "Sharing my knowledge with anyone willing to listen"
    tagline = "ðŸŽ¤ Speaker ðŸ“š Reader ðŸŽ­ Improv"